name: hostel_management
description: "A new Flutter project for Hostel Management."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # অটো-লগইন এবং ডাটা সেভ করার জন্য
  shared_preferences: ^2.2.2

  # গ্যালারি বা ক্যামেরা থেকে ছবি সিলেক্ট করার জন্য
  image_picker: ^1.0.7

  # প্রোফাইল পিকচার স্থায়ীভাবে সেভ করার জন্য
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # এসেট সেকশন (নিশ্চিত করুন ফোল্ডারটি পিসিতে আছে)
  assets:
    - assets/images/